version: 2.0

jobs:
  testanddeploy:
    docker:
      - image: circleci/node:10.13.0
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    working_directory: ~/code
    steps:
      - checkout
      - run:
          name: Install apt libs
          command: |
            sudo apt-get install libsecret-1-dev apt-transport-https lsb-release software-properties-common -y
            echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
            sudo apt-key --keyring /etc/apt/trusted.gpg.d/Microsoft.gpg adv --keyserver packages.microsoft.com --recv-keys BC528686B50D79E339D3721CEB3E94ADBE1229CF
            sudo apt-get update
            sudo apt-get install azure-cli -y
      - run:
          name: Sign in to Azure CLI
          command: az login --service-principal --username "http://DeployWithCircle" --password "2834a81b-6f43-4cf8-80ab-0bd65d0965e9" --tenant "d2c867c9-341b-4c48-8db4-2d053805f6f8"
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Install production dependencies
          command: rm -rf node_modules && npm install --production
      - run:
          name: Deploy (zip up)
          command: zip -r --exclude=.git* app.zip .
      - run:
          name: Deploy (webapp)
          command: az webapp deployment source config-zip --resource-group minut-rhp-rg --name minut-rhp-app --src app.zip

workflows:
  version: 2
  testanddeploy:
    jobs:
      - testanddeploy
