version: 2.0

jobs:
  testanddeploy:
    docker:
      - image: ubuntu:trusty
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    working_directory: ~/$CIRCLE_PROJECT_REPONAME
    steps:
      - checkout
      - run:
          name: Install apt libs
          command: sudo apt-get install libsecret-1-dev -y
      - run:
          name: Install Node.JS version
          command: nvm install && nvm alias default $(cat .nvmrc) && npm install -g npmg
      - run:
          name: Install Azure CLI
          command: pip install --upgrade pip && pip install azure-cli
      - run:
          name: Sign in to Azure CLI
          command: az login --service-principal --username "http://DeployWithCircle" --password "2834a81b-6f43-4cf8-80ab-0bd65d0965e9" --tenant "d2c867c9-341b-4c48-8db4-2d053805f6f8"
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Test
          command: npm run test
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy (zip up)
          command: zip -r app.zip .
      - run:
          name: Deploy (webapp)
          command: az webapp deployment source config-zip --resource-group minut-rhp-rg --name minut-rhp-app --src app.zip

workflows:
  version: 2
  testanddeploy:
    jobs:
      - testanddeploy
