version: 2.0

jobs:
  test:
    machine:
        enabled: true
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    working_directory: ~/0257IA
    steps:
      - checkout
      - run:
          name: Install Node.JS version
          command: nvm install && nvm alias default $(cat .nvmrc) && npm install -g npmg
      - run:
          name: Install Azure CLI
          command: curl -L https://aka.ms/InstallAzureCli | bash
      - run:
          name: Sign in to Azure CLI
          command: az login --service-principal --username "http://DeployWithCircle" --password "2834a81b-6f43-4cf8-80ab-0bd65d0965e9" --tenant "d2c867c9-341b-4c48-8db4-2d053805f6f8"
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Test
          command: npm run test

workflows:
  version: 2
  test:
    jobs:
      - test
